# Copyright (C) 2018-2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform --version

stages:
  - validate
  - plan
  - apply

.terraform_github_setup: &terraform_github_setup |
  cd github
  terraform init foo
  terraform init zeiot
  terraform init pilotariak


.terraform_gitlab_setup: &terraform_gitlab_setup |
  cd github
  terraform init zeiot



validate:github:
  stage: validate
  script:
    - *terraform_github_setup
    - pwd
    - terraform validate -var-file=foo/galactus.tfvars.example foo
    - terraform validate -var-file=zeiot/galactus.tfvars.example zeiot
    - terraform validate -var-file=pilotariak/galactus.tfvars.example pilotariak

validate:gitlab:
  stage: validate
  script:
    - *terraform_github_setup
    - pwd
    - terraform validate -var-file=zeiot/galactus.tfvars.example zeiot

plan:github:
  stage: plan
  script:
    - *terraform_github_setup
    - pwd
    - terraform plan -out "planfile" -var-file=foo/galactus.tfvars.example foo
    - terraform plan -out "planfile" -var-file=zeiot/galactus.tfvars.example zeiot
    - terraform plan -out "planfile" -var-file=pilotariak/galactus.tfvars.example pilotariak
  dependencies:
    - validate:github
  artifacts:
    paths:
      - planfile

# apply:github:
#   stage: apply
#   script:
#     - terraform apply -input=false "planfile"
#   dependencies:
#     - plan
#   when: manual
